# Generated by Django 5.0.6 on 2024-05-25 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_dateofbirth_remove_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfile',
            name='csvfile',
            field=models.FileField(upload_to=''),
        ),
    ]
