# Generated by Django 5.0.6 on 2024-05-25 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_user_myuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfile',
            name='csvfile',
            field=models.FileField(upload_to='csvfiles/'),
        ),
    ]
