# Generated by Django 5.0.6 on 2024-05-25 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_userfile_user_delete_myuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfile',
            name='csvfile',
        ),
        migrations.AddField(
            model_name='userfile',
            name='file',
            field=models.FileField(default='', upload_to='files/'),
            preserve_default=False,
        ),
    ]
