# Generated by Django 5.0.6 on 2024-05-27 03:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0009_remove_userfile_csvfile_userfile_file"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userfile",
            old_name="conclusion",
            new_name="best_model",
        ),
        migrations.RemoveField(
            model_name="userfile",
            name="file",
        ),
        migrations.RemoveField(
            model_name="userfile",
            name="photo",
        ),
        migrations.AddField(
            model_name="userfile",
            name="best_result",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="userfile",
            name="data_file",
            field=models.FileField(default="blank_file.csv", upload_to="save_files/"),
        ),
    ]
